const DEFAULT_TITLE = "T3 Template";
const DEFAULT_DESCRIPTION = "T3 Template";

const CONSTANTS = {
  DEFAULT_TITLE: DEFAULT_TITLE,
  DEFAULT_AUTHOR: "Antarctic Solutions Inc.",
  DEFAULT_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS: ["next", "T3", "boilerplate"],
  DEFAULT_SITE_NAME: "T3 Template",
  DEFAULT_BASE_URL: "",
  DEFAULT_PREVIEW_IMG: "",
  DEFAULT_TWITTER_TITLE: DEFAULT_TITLE,
  DEFAULT_TWITTER_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_GOOGLE_ANALYTICS: "",
};

export default CONSTANTS;
