const DEFAULT_TITLE = "Shorter";
const DEFAULT_DESCRIPTION = "A URL Shortener for free!";

const CONSTANTS = {
  DEFAULT_TITLE: DEFAULT_TITLE,
  DEFAULT_AUTHOR: "Andrew Li",
  DEFAULT_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_KEYWORDS: ["url", "shortener", "url-shorten"],
  DEFAULT_SITE_NAME: "Shorter",
  DEFAULT_BASE_URL: "",
  DEFAULT_PREVIEW_IMG: "",
  DEFAULT_TWITTER_TITLE: DEFAULT_TITLE,
  DEFAULT_TWITTER_DESCRIPTION: DEFAULT_DESCRIPTION,
  DEFAULT_GOOGLE_ANALYTICS: "",
};

export default CONSTANTS;
